account/urls.py
from django.conf.urls import url 
from django.contrib.auth import views as auth_views


from . import views 

urlpatterns = [
				url(r'^login/$', auth_views.login, name = 'login'),
				url(r'^logout/$', auth_views.logout, name = 'logout'),
				url(r'^logout-then-login/$', auth_views.logout_then_login, name = 'logout_then_login'),
				#url(r'^password-change/$', auth_views.PasswordChangeView.as_view(), name = 'password_change'),
				#url(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(), name = 'password_change_done'),
				url(r'^dashboard/$', views.dashboard, name = 'dashboard'),
				url(r'^edit/$', views.edit, name = 'edit'),
				url(r'^list/$', views.users_list, name = 'users_list'),
				url(r'^register/$', views.register, name = 'register'),
				url(r'^users/(?P<username>[-\w]+)/$', views.user_detail, name = 'user_detail'),
				]

zeets/urls.py
from django.conf.urls import url 


from . import views 

urlpatterns = [
				url(r'^post/$', views.post_zeet, name = 'post'),
				url(r'^feed/$', views.feed, name = 'feed'),
				url(r'^zeet/$', views.all_zeets, name = 'home'),
				url(r'^edit-zeet/(?P<zeet_id>[0-9]+)/$', views.edit_zeet, name = 'edit_zeet'),
				url(r'^delete/(?P<zeet_id>[0-9]+)/$', views.delete_zeet, name = 'delete'),
				url(r'^comments/(?P<zeet_id>[0-9]+)/$', views.comment, name = 'comment'),
				url(r'^delete-comment/(?P<comment_id>[0-9]+)/$', views.delete_comment, name = 'delete_comment'),
				url(r'^add_like/(?P<zeet_id>[0-9]+)/$', views.add_like, name = 'add_like'),
				url(r'^remove_like/(?P<zeet_id>[0-9]+)/$', views.remove_like, name = 'remove_like'),
				]

zitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace = 'account', app_name = 'account')),
    url(r'^', include('zeets.urls', namespace = 'zeets', app_name = 'zeets')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

zeets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User 
from django.conf import settings
# Create your models here.
class Zeet(models.Model):
	zeeter = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = 'zeets_created')
	body = models.CharField(max_length = 140, help_text = "140 characters only :P")
	created = models.DateTimeField(auto_now = True)
	image = models.ImageField(blank = True, upload_to = '%Y/%m/%d/images/')
	likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'zeets_like', blank = True, default = 0)

	class Meta:
		ordering = ['-created']

	def __str__(self):
		return self.created 

class Comment(models.Model):
	zeet = models.ForeignKey(Zeet, related_name = 'comments')
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = 'commented')
	body = models.CharField(max_length = 350, help_text = "350 characters only")
	photo = models.ImageField(blank = True, upload_to = "%Y/%m/%d/images/")
	created = models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']

	def __str__(self):
		return "{} commented on {}".format(self.user, self.zeet)

zeets/forms.py
from django import forms


from .models import Zeet, Comment

class ZeetPostForm(forms.ModelForm):
	class Meta:
		model = Zeet
		fields = ['body', 'image']


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['body']

zeets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from actions.utils import create_action
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
from .models import Zeet, Comment
from .forms import ZeetPostForm, CommentForm

def all_zeets(request):
	zeets = Zeet.objects.filter(zeeter = request.user)
	return render(request, 'zeets/home.html', {'zeets':zeets})

@login_required
def post_zeet(request):
	if request.method == 'POST':
		form = ZeetPostForm(data = request.POST, files = request.FILES)
		if form.is_valid():
			new_zeet = form.save(commit = False)
			new_zeet.zeeter = request.user
			new_zeet.save()
			create_action(request.user, 'posted a new zeet named', new_zeet)
			return redirect('zeets:feed')
	else:
		form = ZeetPostForm()
	return render(request, 'zeets/post.html', {'form':form})

@login_required
def edit_zeet(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	if request.method == 'POST':
		form = ZeetPostForm(data = request.POST, instance = zeet, files = request.FILES)
		if form.is_valid():
			form.save()
			return redirect('zeets:home')
	else:
		form = ZeetPostForm(instance = zeet)
	return render(request, 'zeets/post.html', {'zeet':zeet, 'form':form})

@login_required
def delete_zeet(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	zeet.delete()
	messages.info(request, 'Zeet was successfully deleted')
	return redirect('zeets:home')

@login_required
def comment(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	comments = zeet.comments.all()
	if request.method == 'POST':
		form = CommentForm(data = request.POST)
		if form.is_valid():
			new_comment = form.save(commit = False)
			new_comment.zeet = zeet 
			new_comment.user = request.user 
			new_comment.save()
			create_action(request.user, 'commented on', zeet)
	else:
		form = CommentForm()
	return render(request, 'zeets/comment.html', {'zeet':zeet, 'comments':comments, 'form':form})

@login_required
def delete_comment(request, comment_id):
	comment = get_object_or_404(Comment, pk = comment_id)
	comment.delete()
	messages.info(request, 'comment was deleted')
	return redirect('zeets:home')

@login_required
def feed(request):
	zeets = Zeet.objects.all()
	return render(request, 'zeets/feed.html', {'zeets':zeets})

@login_required
def add_like(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	zeet.likes.add(request.user)
	create_action(request.user, 'likes', zeet)
	return redirect('zeets:feed')

@login_required
def remove_like(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	zeet.likes.remove(request.user)
	return redirect('zeets:feed')

zeets/templates/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>                        
		      </button>
		      {% if request.user.is_authenticated %}
		      	<a class="navbar-brand" href="{% url "zeets:feed" %}">Zitter</a>
		      {% else %}
		      	<a class="navbar-brand" href="{% url "account:login" %}">Zitter</a>
		      {% endif %}
		    </div>
		    <div class="collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav navbar-right">
		      	{% if request.user.is_authenticated %}
		      		<li><a href="{% url "zeets:post" %}"><span class="glyphicon glyphicon-pencil"></span></a></li>
		      		<li><a href="{% url "zeets:feed" %}">feed</a></li>
		      		<li><a href="{% url "account:dashboard" %}"><span class="glyphicon glyphicon-user"></span>({{ user.username }})</a>
		        	<li><a href="{% url "account:users_list" %}">People</a></li>
		      		<li><a href="{% url "account:logout_then_login" %}">logout</a></li>
		      	{% else %}
		      		<li><a href="{% url "account:register" %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
		        	<li><a href="{% url "account:login" %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
		      	{% endif %}
		        
		      </ul>
		    </div>
		  </div>
		</nav>
		<div class="row">
			<div class="col-md-8">
				{% block content %}
				{% endblock %}
			</div>
			{% if messages %}
				<br>
					{% for message in messages %}
						<br>
						<li>{{ message|safe }}<a href="{% url "zeets:home" %}" class="close">✖</a></li>
					{% endfor %}
				</ul>
			{% endif %}
			<div class="col-md-4">
				{% block side %}
				{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>