account/urls.py
from django.conf.urls import url 
from django.contrib.auth import views as auth_views


from . import views 

urlpatterns = [
				url(r'^login/$', auth_views.login, name = 'login'),
				url(r'^logout/$', auth_views.logout, name = 'logout'),
				url(r'^logout-then-login/$', auth_views.logout_then_login, name = 'logout_then_login'),
				#url(r'^password-change/$', auth_views.PasswordChangeView.as_view(), name = 'password_change'),
				#url(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(), name = 'password_change_done'),
				url(r'^dashboard/$', views.dashboard, name = 'dashboard'),
				url(r'^edit/$', views.edit, name = 'edit'),
				url(r'^list/$', views.users_list, name = 'users_list'),
				url(r'^register/$', views.register, name = 'register'),
				url(r'^users/(?P<username>[-\w]+)/$', views.user_detail, name = 'user_detail'),
				]

zeets/urls.py
from django.conf.urls import url 


from . import views 

urlpatterns = [
				url(r'^post/$', views.post_zeet, name = 'post'),
				url(r'^feed/$', views.feed, name = 'feed'),
				url(r'^zeet/$', views.all_zeets, name = 'home'),
				url(r'^edit-zeet/(?P<zeet_id>[0-9]+)/$', views.edit_zeet, name = 'edit_zeet'),
				url(r'^delete/(?P<zeet_id>[0-9]+)/$', views.delete_zeet, name = 'delete'),
				url(r'^comments/(?P<zeet_id>[0-9]+)/$', views.comment, name = 'comment'),
				url(r'^delete-comment/(?P<comment_id>[0-9]+)/$', views.delete_comment, name = 'delete_comment'),
				url(r'^add_like/(?P<zeet_id>[0-9]+)/$', views.add_like, name = 'add_like'),
				url(r'^remove_like/(?P<zeet_id>[0-9]+)/$', views.remove_like, name = 'remove_like'),
				]

zitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace = 'account', app_name = 'account')),
    url(r'^', include('zeets.urls', namespace = 'zeets', app_name = 'zeets')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

zeets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User 
from django.conf import settings
# Create your models here.
class Zeet(models.Model):
	zeeter = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = 'zeets_created')
	body = models.CharField(max_length = 140, help_text = "140 characters only :P")
	created = models.DateTimeField(auto_now = True)
	image = models.ImageField(blank = True, upload_to = '%Y/%m/%d/images/')
	likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'zeets_like', blank = True, default = 0)

	class Meta:
		ordering = ['-created']

	def __str__(self):
		return self.created 

class Comment(models.Model):
	zeet = models.ForeignKey(Zeet, related_name = 'comments')
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = 'commented')
	body = models.CharField(max_length = 350, help_text = "350 characters only")
	photo = models.ImageField(blank = True, upload_to = "%Y/%m/%d/images/")
	created = models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ['-created']

	def __str__(self):
		return "{} commented on {}".format(self.user, self.zeet)

zeets/forms.py
from django import forms


from .models import Zeet, Comment

class ZeetPostForm(forms.ModelForm):
	class Meta:
		model = Zeet
		fields = ['body', 'image']


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['body']

zeets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from actions.utils import create_action
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
from .models import Zeet, Comment
from .forms import ZeetPostForm, CommentForm

def all_zeets(request):
	zeets = Zeet.objects.filter(zeeter = request.user)
	return render(request, 'zeets/home.html', {'zeets':zeets})

@login_required
def post_zeet(request):
	if request.method == 'POST':
		form = ZeetPostForm(data = request.POST, files = request.FILES)
		if form.is_valid():
			new_zeet = form.save(commit = False)
			new_zeet.zeeter = request.user
			new_zeet.save()
			create_action(request.user, 'posted a new zeet named', new_zeet)
			return redirect('zeets:feed')
	else:
		form = ZeetPostForm()
	return render(request, 'zeets/post.html', {'form':form})

@login_required
def edit_zeet(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	if request.method == 'POST':
		form = ZeetPostForm(data = request.POST, instance = zeet, files = request.FILES)
		if form.is_valid():
			form.save()
			return redirect('zeets:home')
	else:
		form = ZeetPostForm(instance = zeet)
	return render(request, 'zeets/post.html', {'zeet':zeet, 'form':form})

@login_required
def delete_zeet(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	zeet.delete()
	messages.info(request, 'Zeet was successfully deleted')
	return redirect('zeets:home')

@login_required
def comment(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	comments = zeet.comments.all()
	if request.method == 'POST':
		form = CommentForm(data = request.POST)
		if form.is_valid():
			new_comment = form.save(commit = False)
			new_comment.zeet = zeet 
			new_comment.user = request.user 
			new_comment.save()
			create_action(request.user, 'commented on', zeet)
	else:
		form = CommentForm()
	return render(request, 'zeets/comment.html', {'zeet':zeet, 'comments':comments, 'form':form})

@login_required
def delete_comment(request, comment_id):
	comment = get_object_or_404(Comment, pk = comment_id)
	comment.delete()
	messages.info(request, 'comment was deleted')
	return redirect('zeets:home')

@login_required
def feed(request):
	zeets = Zeet.objects.all()
	return render(request, 'zeets/feed.html', {'zeets':zeets})

@login_required
def add_like(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	zeet.likes.add(request.user)
	create_action(request.user, 'likes', zeet)
	return redirect('zeets:feed')

@login_required
def remove_like(request, zeet_id):
	zeet = get_object_or_404(Zeet, pk = zeet_id)
	zeet.likes.remove(request.user)
	return redirect('zeets:feed')

zeets/templates/zeets/comment.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
	zitter-home
{% endblock %}

{% block content %}
	<br>
	<div class="row">
		<div class="col-md-8">
			<b>{{ zeet.zeeter }}</b>
			<small>{{ zeet.created }}</small>
			<p>{{ zeet.body|linebreaks }}</p>
			{% if zeet.image %}
				<img src="{% if zeet.image %}{{ zeet.image.url }}{% endif %}" width="250" height="250" class="img-rounded">
			{% endif %}<br>
			<a href="{% url "zeets:edit_zeet" zeet.pk %}">edit</a>
			<a style="color:red;" href="{% url "zeets:delete" zeet.pk %}">delete</a><hr>
			{% with comments.count as total_comments %}
				<b>{{ total_comments }} comment{{ total_comments|pluralize }}</b>
			{% endwith %}
			{% for comment in comments %}
				<p class="info">
					Comment {{ forloop.counter }} by {{ comment.user }}
					{{ comment.created }}
				</p>
					{{ comment.body|linebreaks }}
					<a style="color:red;" href="{% url "zeets:delete_comment" comment.pk %}">delete</a><hr>
			{% empty %}
				<p>There are no comments yet.</p>
			{% endfor %}
		</div>
		<div class="col-md-4">
			{% if new_comment %}
				<h2>Your comment has been added.</h2>
			{% else %}
				<h4>Add a new comment</h4>
				<form action="." method="post">
				{% csrf_token %}
				{{ form|crispy }}
				<button class="btn btn-primary btn-block">comment</button>
				</form>
			{% endif %}
		</div>
	</div>
{% endblock %}

{% block side %}
	<img src="{% static "img/post.png" %}" width="250" height="200">
{% endblock %}

zeets/templates/zeets/feed.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
	zitter-feed
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-7">
	{% if zeets %}
		{% for zeet in zeets %}
				<h4><a href="{% url "account:user_detail" zeet.zeeter %}">{{ zeet.zeeter.profile.image.url }}{{ zeet.zeeter }}</a></h4>
				<div class="thumbnail">
					{% if zeet.image %}
						<img src="{{ zeet.image.url }}" class="img-rounded" width="250" height="250">
					{% endif %}
					<div class="caption">
						<p><b>{{ zeet.likes.count }} like{{ zeet.likes.count|pluralize }}, 
						{{ zeet.comments.count }} comment{{ zeet.comments.count|pluralize }}</b></p>
				        	<p>
				        		{% if request.user not in zeet.likes %}
				        			<a href="{% url "zeets:remove_like" zeet.pk %}">
				        				<button class="btn btn-primary btn-md"><span class="glyphicon glyphicon-thumbs-down"></span></button>
				        			</a>
				        		{% else %}
				        			<a href="{% url "zeets:add_like" zeet.pk %}">		        				
				        				<button class="btn btn-primary btn-md"><span class="glyphicon glyphicon-thumbs-up"></span></button>
				        			</a>
				        		{% endif %}
				        		{% if request.user not in zeet.likes %}
				        			<a href="{% url "zeets:add_like" zeet.pk %}">
				        				<button class="btn btn-primary btn-md"><span class="glyphicon glyphicon-thumbs-up"></span></button>
				        			</a>
				        		{% else %}
				        			<a href="{% url "zeets:remove_like" zeet.pk %}">	        				
				        				<button class="btn btn-primary btn-md"><span class="glyphicon glyphicon-thumbs-down"></span></button>
				        			</a>
				        		{% endif %}
				        		<a href="{% url "zeets:comment" zeet.pk %}" style="color:green;"><button class="btn btn-success btn-md"><span class="glyphicon glyphicon-comment"></span></button></a>
				        	</p>
					    <p>{{ zeet.body|linebreaks }}</p>
						<p><small>{{ zeet.created }}</small></p>
					</div>
				</div><hr>
		{% endfor %}
	{% else %}
		<p>No zeets yet. Start zeeting <a href="{% url "zeets:post" %}">here</a>.</p>
	{% endif %}
</div>
</div>
{% endblock %}

zeets/templates/zeets/home.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
	zitter-home
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12 offset-12">
			<br><br>
			{% if zeets %}
					{% for zeet in zeets %}
						<b>Posted by {{ zeet.zeeter }}</b><br>	
						<small>{{ zeet.created }}</small>
						<a href="{% url "zeets:edit_zeet" zeet.pk %}">(edit zeet)</a>
						<br>
						{% if zeet.image %}
							<img src="{% if zeet.image %}{{ zeet.image.url }}{% endif %}" width="250" height="250" class="img-rounded">
						{% endif %}
						<p>{{ zeet.body|linebreaks }}</p>
						<a style="color: green;" href="{% url "zeets:comment" zeet.pk %}">comment</a>
						<button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal" style="background-color: #990000;"><span class="glyphicon glyphicon-trash"></span></button>

						  <!-- Modal -->
						  <div class="modal fade" id="myModal" role="dialog">
						    <div class="modal-dialog">
						    
						      <!-- Modal content-->
						      <div class="modal-content">
						        <div class="modal-header">
						          <button type="button" class="close" data-dismiss="modal">&times;</button>
						          <h4 class="modal-title" style="color:red;">Delete zeet</h4>
						        </div>
						        <div class="modal-body">
						          <p>Are you sure you want to delete this zeet?</p>
						          <a href="{% url "zeets:delete" zeet.pk %}"><button class="btn btn-danger btn-md">Yes, delete</button></a>
						        </div>
						        <div class="modal-footer">
						          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						        </div>
						      </div>
						      
						    </div>
						  </div>
						<hr>
					{% endfor %}
			{% else %}
				<p>Oops! No zeets yet. Start Zeeting <a href="{% url "zeets:post" %}">here</a>.</p>
			{% endif %}
		</div>
	</div>
{% endblock %}

zeets/templates/zeets/post.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
	zitter-home
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-7">
			<h4>What's happening?</h4>
			<form action="." method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form|crispy }}
				<button class="btn btn-primary btn-block">zeet</button>
			</form>
		</div>
	</div>
{% endblock %}